### ISSUE TITLE
Update scBasset tutorials to explain motif scoring

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scvi-tutorials#114]
Show new functionality from https://github.com/scverse/scvi-tools/pull/2010

**Comment by adamgayoso** [comment]
@jacobkimmel I know you're probably busy but just let us know if you can do this!

**Comment by jacobkimmel** [comment]
@adamgayoso I'll knock this out over the weekend!

**Comment by martinkim0** [comment]
Closed via #125
