### ISSUE TITLE
reference mapping

### ISSUE THREAD

**Issue by Sirin24** [scverse/scvi-tutorials#272]
i am following https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scrna/scarches_scvi_tools.html#reference-mapping-with-scanvi

>>> import os
>>> import tempfile
>>> import anndata
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> import pandas as pd
>>> import scanpy as sc
>>> import scrublet as scr
>>> import scvi
>>> import seaborn as sns
>>> import torch

>>> scvi_model = SCVI(adata, **arches_params)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'SCVI' is not defined

**Comment by ori-kron-wis** [comment]
there is currently a bug in https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scrna/scarches_scvi_tools.html#reference-mapping-with-scanvi for v1.1.x that will be solved in v1.2.x

see 
https://github.com/scverse/scvi-tools/issues/2934
