### ISSUE TITLE
Update scArches tutorials to discuss encode_covariates

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tutorials#294]
https://github.com/scverse/scvi-tools/issues/2331

**Comment by ori-kron-wis** [comment]
add:
Train reference
We train the reference using the standard SCVI workflow, except we add a few non-default parameters that were identified to work well with scArches. It is essential to encode covariates here as this allows scArches to map new batches in the encoder to the existing data and thereby provides batch integration. (edited)
