### ISSUE TITLE
Lung dataset has no raw counts

### ISSUE THREAD

**Issue by emdann** [scverse/scvi-tutorials#66]
Hello,
I was trying to reproduce the [Atlas-level integration tutorial](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/harmonization.html). The dataset downloaded via figshare is supposed to store raw counts in `adata.layers['counts']`, but these values here don't really look like counts.

```py
adata = sc.read(
    "data/lung_atlas.h5ad",
    backup_url="https://figshare.com/ndownloader/files/24539942",
)

adata.layers['counts'].data
``` 
```pytb
array([1.       , 1.       , 1.       , ..., 1.1387753, 2.2072291,
       1.0936011], dtype=float32)
```

Are these some sort of soup-corrected counts, and does it matter?

**Comment by emdann** [comment]
Thank you for clarifying! The tutorial says
>Note that this dataset has the counts already separated in a layer. Here, adata.X contains log transformed scran normalized expression.  
Maybe worth specifying it's SoupX corrected counts?

**Comment by adamgayoso** [comment]
This is a good point, we should clarify that while we generally expect integer UMI counts, technically we can handle continuous values that are intended to represent counts (e.g., soupx). Also with smartseq2 data, we typically normalize the reads per gene to the median gene length. We actually have this info box in the docs site version of the tutorial.

@jjhong922 can you please add into the main overview tutorial this info about pseudocounts etc? There's already an info box in that one too about raw counts.


<img width="862" alt="Screen Shot 2022-06-16 at 8 30 36 AM" src="https://user-images.githubusercontent.com/10859440/174016684-4ba57854-faa8-4a9f-a059-a10e694b29fa.png">
