### ISSUE TITLE
Update the vignette

### ISSUE THREAD

**Issue by emanuelavilla** [scverse/scvi-tutorials#78]
Hello!

I am using your scANVI tool but I have to report that the vignette is old. For example, there is the command 

scvi$data$setup_anndata(adata_both, labels_key="celltype", batch_key="batch")

However, it worked with scvi-tool v=0.8. With version 0.15, the command is 

scvi$model$SCVI$setup_anndata(adata_both, labels_key="celltype", batch_key="batch")

I think that it would be important to maintain the vignette update because many people, including people approaching the bioinformatic, have access. 

Thanks!

Emanuela

**Comment by adamgayoso** [comment]
@martinkim0 this can be fixed by just editing the file itself without running anything
